issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst 
        - err113 

linters-settings:
  nlreturn:
    # Allow 2 lines max to have a return statement without a new line before it
    block-size: 3

  gocritic:
    disabled-checks:
      - "paramTypeCombine"
      - "unnamedResult"
    enabled-tags:
      - "performance"
      - "style"
      - "diagnostic"

  govet:
    enable-all: true
    disable:
      - fieldalignment

linters:
  enable-all: true
  disable: 
    - gochecknoglobals 
    - depguard 
    - exhaustruct 
    - lll
    - wsl 
    - wrapcheck 
    - varnamelen 
    - testpackage 
    - funlen 
    - exportloopref 
    - godot 
    - godox

